.gitignore
I am not sure when the bin/ directory is created, but this way it works for mustang/ as well.
=> gitignore bin/ recursively

mustang/pom.xml, mustang/src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDAllowanceCharge.java, mustang/src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDExportableItem.java, mustang/src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDExportableTransaction.java, mustang/src/main/java/org/mustangproject/ZUGFeRD/VATAmount.java, mustang/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExporter.java, mustang/src/test/java/org/mustangproject/ZUGFeRD/MustangReaderWriterEdgeTest.java, mustang/src/test/java/org/mustangproject/ZUGFeRD/MustangReaderWriterTest.java, nbactions.xml, pdfa3-sample/pom.xml, pom.xml
- Fixed validation error due to missing tax category field
- Fixed decimal places for all amount / price fields
- Updated to PDFBOX 1.8.10
- Implemented support for Header and Item allowances / charges and service charges.
- Introduced new interface IZUGFeRDAllowanceCharge for allowance and charges on all levels
- added getZFAllowances(), getZFCharges() and getZFLogisticsServiceCharges() functions to Interface IZUGFeRDExportableTransaction -> can be null
- added getItemAllowances() and getItemCharges() functions to Interface IZUGFeRDExportableItem -> can be null
- Improved totals calculation -> precalculated totals to reduce item loops
=> Validation error fixes and support for allowances, charges and service charges

pdfa3-sample/src/main/java/pdfbox/PDFA3FileAttachment.java
PDFA3FileAttachment.pdf does not conform to PDF/A.
Validate PDF/A 3-a File online at http://www.pdf-tools.com/pdf/validate-pdfa-online.aspx
I found how to solve the problem at https://www.mail-archive.com/search?l=users@pdfbox.apache.org&q=subject:%22How+can+I+embed+files+in+PDF%2FA-3a%3F%22&o=newest&f=1
I hope you find it useful
=> fix validation error, file specification not associated with an object

mustang/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExporter.java
When I use the ZUGFeRDExporter in my application I get these warnings:
> WARN COSDocument:637 - Warning: You did not close a PDF Document
(Note that the warning comes from a destructor of pdfbox. So this warning will only appear in applications that run long enough to trigger the garbage collector)
These warnings will disappear when I call `zugFeRDExporter.getDoc().close();` one I am done with the Exporter. However I this seems unintuitive and it breaks the law of demeter. I think the exporter should have a close method, which delegates the close-call to the document.
=> Make ZUGFeRDExporter closeable to avoid warning "You did not close a PDF Document"

mustang/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExportException.java, mustang/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExporter.java
This is a subset of what was proposed in PR #18, so we can review and discuss in smaller steps.
I removed JAXB exceptions from public API to improve encapsulation. I think the user of the library should not know which method is used to serialize the objects to XML. This also makes it possible to exchange/upgrade the XML generation library without changing the public API in case this becomes necessary. As far as I can tell there is nothing a user could do about a JAXBException if he caught one, because he has no influence of the usage.
=> Removed JAXBExceptions from the public API of the ZUGFeRDExporter

mustang/src/main/java/org/mustangproject/ZUGFeRD/PDFAConformanceLevel.java, mustang/src/main/java/org/mustangproject/ZUGFeRD/XMPSchemaZugferd.java, mustang/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDConformanceLevel.java, mustang/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExporter.java
This is a subset of what is proposed in #18.
This pull request proposes that the conformance levels for PDF documents ("A", "B", "U") and ZUGFeRD documents (BASIC, COMFORT, EXTENDED) are used as enums and not as strings, to improve readability and eliminate the possibility of illegal conformance levels being used by the user.
=> Use enum values for PDF/A conformance levels and ZUGFeRD conformance levels

mustang/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDConformanceLevel.java, mustang/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExportException.java, mustang/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExporter.java, mustang/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExporterFromA1Factory.java, mustang/src/main/java/org/mustangproject/ZUGFeRD/model/PDFAConformanceLevel.java
In extension to #17 I'd propose to change the API of the `ZUGFeRDExporter`. The changes in this pull request should be backward compatible, so that users have time to adjust.
The changes are as follows:
1. I extracted the `ZUGFeRDExporterFromA1Factory` from the `ZUGFeRDExporter`. I already outlined the reasons for that in #17. In short: This removes temporal couplings, which force the user to call methods in a specified order without the order being fully apparent: Settings which only play a role for PDF conversion are only available when actually performing a conversion and also only before doing the conversion.
2. I removed JAXB exceptions from public API to improve encapsulation. I think the user of the library should not know which method is used to serialize the objects to XML. This …
=> Proposal on changes of the ZUGFeRDExporter-API

pom.xml, src/main/java-templates/org/mustangproject/ZUGFeRD/Version.java, src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExporter.java, src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExporterFromA1Factory.java
You [previously mentioned](https://github.com/ZUGFeRD/mustangproject/pull/18#issuecomment-303210373) that you'd prefer to read the version number from the maven POM file rather than maintaining an additional constant in the project.
I think that makes sense. This pull request will do just that. When compiling with maven, it will add a class `Version` with a constant `VERSION` to the target/generated-sources directory, which can then be accessed normally.
Note that your IDE might complain about the missing file (although the project will build normally with maven): Build the project once with maven, so that maven generates the version class and then, in your IDE, mark the directory `target/generated-sources/java-templates` as "generated sources root" (IntelliJ IDEA) or only "src" or …
=> Use version from pom.xml instead java constant

src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExporter.java
The method `PDFattachZugferdFile` in class `ZUGFeRDExporter` has Javadoc for a parameter `doc`, but this parameter does not exist on the method, so the JavaDoc should be removed.
=> Remove javadoc for not-existing parameter

src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDTransactionModelConverter.java
Die Rechnung wird in einer Fremdwährung z.B. CHF (Schweitzer Franken) gestellt. Auf dem PDF wir der korrekte Währungscode angegeben, das ZUGFeRD-XML bekommt aber immer EUR.
So bekommt man anstelle einer 100,00 CHF Rechnung eine 100,00 EUR Rechnung.
=> Wrong currency in xml part

src/main/java/org/mustangproject/toecount/Toecount.java
As discussed in #66 
I reworked only the `Toecount.java` file to offer more input arguments.
If an input argument is not set, then the user will be prompted like before (no change in behavior here).
The help message looks like this now:
```
Mustangproject.org 1.5.5-SNAPSHOT
A Apache Public License library and command line tool for statistics on PDF invoices with
ZUGFeRD Metadata (http://www.zugferd.org)
Usage: [-d,--directory] [-l,--listfromstdin] [-i,--ignorefileextension] | [-c,--combine] | [-e,--extract] | [-u,--upgrade] | [-a,--a3only] | [-h,--help]
* Count operations
-d, --directory count ZUGFeRD files in directory to be scanned
If it is a directory, it will recurse.
-l, --listfromstdin     count ZUGFeRD files from a list of linefeed separated files on runtime.
It will start once a …
```
=> Commandline: ability to set input parameters

src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDExportableContact.java, src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDExportableTransaction.java, src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDTransactionModelConverter.java
IZUGFeRDExportableTransaction: Interface-Methodes switched to default, so they don't have to be implementend in inheriting classes when not needed
IZUGFeRDExportableContact: added getID() to return a unique customer ID
assigned by the seller > BuyerTradeParty.ID
ZUGFeRDTransactionModelConverter: getBuyer() and getSeller() adjusted.
add ID to XML if available
removed unnecessary this. and typecast
=> Interface Methodes to default; Seller- / BuyerTradeParty: ID added; removed unnessesary this/typecast code

src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDImporter.java, src/test/java/org/mustangproject/ZUGFeRD/MustangReaderWriterCustomXMLTest.java
I stumbled on this while looking for something else.
Also: MustangReaderWriterTest.java references a resource `/MustangGnuaccountingBeispielRE-20190610_507blanko.pdf`, which is not in the repository.
=> Byte order marks cause unit test failures with Java 1.8

src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDImporter.java
code for #99 :
We look at the first few bytes of the input stream to determine if there is a BOM. The input stream skips the number of bytes that have been detected before being parsed by the DocumentBuilder.
=> skip over BOM in XML input

src/test/java/org/mustangproject/ZUGFeRD/MustangReaderWriterCustomXMLTest.java
This change fixes the build problem and lets `mvn test` succeed.
=> specify charset to avoid platform specific defaults

src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java, src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDTransactionModelConverter.java
I checked the implementation of BigDecimal.toPlainString in OpenJDK 1.8 (and 12) and as far as I can tell, the decimal point comes from the following helper method, which hardcodes the `.`:
```
/* Returns a digit.digit string */
private String getValueString(int signum, String intString, int scale) {
/* Insert decimal point */
StringBuilder buf;
int insertionPoint = intString.length() - scale;
if (insertionPoint == 0) {  /* Point goes right before intVal */
return (signum<0 ? "-0." : "0.") + intString;
} else if (insertionPoint > 0) { /* Point goes inside intVal */
buf = new StringBuilder(intString);
buf.insert(insertionPoint, '.');
if (signum < 0)
buf.insert(0, '-');
} else { /* We must insert zeros between point and intVal */
buf = new StringBuilder(3-insertionPoint + …
```
=> use RoundingMode enumeration and locale-safe BigDecimal.toPlainString

src/main/java/org/mustangproject/ZUGFeRD/CustomXMLProvider.java, src/main/java/org/mustangproject/ZUGFeRD/IProfileProvider.java, src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD1PullProvider.java, src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java, src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExporter.java, src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDTransactionModelConverter.java, src/test/java/org/mustangproject/ZUGFeRD/MustangReaderWriterTest.java
re #113:
This test fails at line 411, which means that the XML file does not reference the BASIC profile, but does reference the EXTENDED profile and hence cannot reference the COMFORT profile as requested in line 400.
=> add failing unit test to prove that the wrong profile is written and then fix it

src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDImporter.java
They've been out of service for a while now and definitely should not be used in new code.
=> deprecate German BLZ and Kontonummer

src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDImporter.java, src/test/java/org/mustangproject/ZUGFeRD/MustangReaderWriterTest.java
The original implementation uses the v2 toplevel element CrossIndustryInvoice, but the actual bank _name_ is only defined in v1.
=> add test for ZUGFeRDImporter.getBankName ... and make it work

src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDImporter.java
sorry, too many parallel PRs.
somehow the wrong `getBankName` (see #125) survived the merging
=> remove zombie definition of getBankName

src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExporter.java, src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExporterFromA3Factory.java, src/main/java/org/mustangproject/toecount/Toecount.java, src/test/java/org/mustangproject/ZUGFeRD/MustangReaderWriterCustomXMLTest.java, src/test/java/org/mustangproject/ZUGFeRD/MustangReaderWriterEdgeTest.java, src/test/java/org/mustangproject/ZUGFeRD/ZF2EdgeTest.java
In most cases this is achieved by using the corresponding factory methods.
Since they have to be set _somehow_, I introduced a new public method
`ZUGFeRDExporter.configure` to keep these calls local to the class.
This is called once in `A3Factory.load(byte[])`.
The deprecated Exporter setters could now be made private but that could
break existing code.
=> avoid deprecated ZUGFeRDExporter methods

pom.xml, src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDDate.java, src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDExportableContact.java, src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDExportableTransaction.java, src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java, src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDDateFormat.java, src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDTransactionModelConverter.java, src/test/java/org/mustangproject/ZUGFeRD/IZUGFeRDDateImpl.java, src/test/java/org/mustangproject/ZUGFeRD/IZUGFeRDExportableTransactionImpl.java, src/test/java/org/mustangproject/ZUGFeRD/ZF2EdgeTest.java, src/test/java/org/mustangproject/ZUGFeRD/ZUGFeRDTransactionModelConverterTest.java
This pull request addresses issue #136 by
- Added possibility to specify delivery date in "week of year" or "month of year" format, through introduction of new IZUGFeRDDate interface. Keeping backward compatibility by providing both methods in IZUGFeRDExportableTransaction
- Added possibility to specify "LineTwo" in Recipient Address
- Limited pdfbox version to maximum 2.0.17 because otherwise 3.0.0-SNAPSHOT was pulled in which was broken because of missing ByteArrayDataSource
=> deliveryDate in different date formats (#136)

src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDExportableTransaction.java, src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDPaymentDiscountTerms.java, src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDPaymentTerms.java, src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java, src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDTransactionModelConverter.java
With this pull request it is possible to define `SpecifiedTradePaymentTerms` in ZUGFeRD 1 in a very comfortable way.
For ZUGFeRD 2 the same classes can be used too, so that it is no longer needed to generate the SpecifiedTradePaymentTerms XML manually.
With these changes it is possible to specify discount terms in both formats.
=> PaymentTerms in ZUGFeRD 1

src/main/resources/stylesheets/ZUGFeRD_1p0_c1p0_s1p0.xslt
- default ZUGFeRD invoice from [ZUGFeRD_1p0_COMFORT_Rechnungskorrektur.pdf](https://github.com/ZUGFeRD/mustangproject/files/4193222/ZUGFeRD_1p0_COMFORT_Rechnungskorrektur.pdf)
- default ZUGFeRD stylesheet (this file)
- latest Saxon library
When trying to create a HTML output for the electronic invoice mentioned above using the following batch file
`java -jar saxon9he.jar ZUGFeRD-invoice.xml ZUGFeRD_1p0_c1p0_s1p0.xslt > output.html
PAUSE`
the following error will be shown in the console
> Warning at char 27 in xsl:value-of/@select on line 1985 column 166 of ZUGFeRD_1p0_c1p0_s1p0.xslt:
SXWN9000: Comparison of xs:untypedAtomic? to xs:boolean will fail unless the first operand is empty
Warning at xsl:for-each on line 2083 column 78 of ZUGFeRD_1p0_c1p0_s1p0.xslt:
SXWN9009: An empty …
=> Refactored comparison operator for ChargeIndicator

libraryBasic/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java
or the program throws a NullPointerException if 'trans' only overwrites 'getPaymentTermDescription()' but not the default 'getDueDate()'.
Fix for issue #155
=> Bugfix in ZUGFeRD2PullProvider.generateXML: try getPaymentTermDescription() before constructing one

libraryBasic/src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDExportablePostalTradeAddress.java, libraryBasic/src/main/java/org/mustangproject/ZUGFeRD/PostalTradeAddress.java, libraryBasic/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDImporter.java, libraryBasic/src/test/java/org/mustangproject/ZUGFeRD/MustangReaderWriterTest.java, libraryBasic/src/test/java/org/mustangproject/ZUGFeRD/ZF2Test.java
Implemented method "getSellerTradePartyAddress" to ZUGFeRDImporter.java which gets an instance of PostalTradeAddress.
Removed method "getISODate" from last Commit due lack of implementation - will be implemented at a later time.
Also Added Tests for "getSellerTradePartyAddress" to match ZF1 and ZF2
=> Add extraction methods

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java
especially for 'BuyerTradeParty' and 'ShipToTradeParty' right now.
Since EN16931 allows only one ID entry for these entries, the ID assigned
by the buyer is prefered over the global ID for now if bot are defined in
the IZUGFeRDExportableTradeParty object.
=> ZUGFeRD2PullProvider: Add write support for GlobalID and ID to buyer addresses

validator/src/main/java/org/mustangproject/validator/Validator.java
If the non-shaded original jar of the validator is packed inside the WEB-INF/lib folder of a WAR, Wildfly is unable to locate the schema file, because of classloading issues. 
See https://developer.jboss.org/thread/80291
Using the context classloader fixes this issue.
=> avoid classloading issues within Wildfly

History.md, Mustang-CLI/src/main/java/org/mustangproject/commandline/Main.java, library/pom.xml, library/src/main/java/org/mustangproject/TradeParty.java
if `<shadedArtifactAttached>` remains `true` the following error will occur `Fehler beim Aufruf von Reflektion auf Zielklassen. Stellen Sie sicher, dass alle referenzierten Klassen im Classpath vorhanden sind: interface javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter` when running sth like `java -jar Mustang-CLI\target\Mustang-CLI-2.0.4-SNAPSHOT.jar --action ubl --source xrechnung.xml`
=> Enabling functionality via Command line, changing POM so no errors occur

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java
This adds support for setting a Contact for the recipient (buyer) TradeParty while using the XRechnung profile in accordance with the format specifications. I've tested this in all relevant combinations and validated the results with the Mustang validator without errors.
Please tell me if anything else is required to get this merged, since I didn't find any contribution guidelines.
=> Allow setting Contact for recipient TradeParty in XRechnung

library/pom.xml
to make UBL conversion work again with Mustang-CLI and in other programs.
ph-commons 9.1.1 is missing some classes needed by en16931-cii2ubl (1.3.0). 
So the dependency to this version in the library broke UBL conversion in all programs 
using mustang library as version 9.1.1 got always included in the jar and not the 
current version.
=> Remove outdated dependency to ph-commons 9.1.1 in library/pom.xml

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java, library/src/test/java/org/mustangproject/ZUGFeRD/XRTest.java
Check if street in the address of the recipient is null.
Add a test that generates invoices with a recipient without a street in the address.
Extract a method in the test to create the invoice with recipient as parameter.
Fixes #222 NullPointerException for TradeParties without street in address
=> #222 Check if street in the address of the recipient is null

Mustang-CLI/src/main/java/org/mustangproject/commandline/Main.java
I noticed that PDF files are still checked for PDF/A conformity even though the  `-i` was set. This fix makes the flag work as it should (at least from my expectations).
=> Set ignoreInputErrors flag before loading PDFs

library/src/main/java/org/mustangproject/ZUGFeRD/Profiles.java, library/src/main/java/org/mustangproject/ZUGFeRD/XMPSchemaZugferd.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExporterFromA3.java
Multiple changes to do with XRechnung and other improvements:
1. Getting a profile by name disregarding the ZUGFeRD version
2. Allowing the XRechnung version to be explicitly set in the
PDF meta-data (must match the version in the attached XML).
3. Change/fix for data relationship in case of MINIMUM and
BASICWL profile. See documentation ZUGFeRD211_EN/
Documentation/ZUGFeRD-2.1.1 - Specification_TA_Part-A.pdf
4. Error handling improvements (exceptions not suppressed)
=> Multiple changes to do with XRechnung and other improvements:

.gitignore, Mustang-CLI/pom.xml, Mustang-CLI/src/test/java/org/mustangproject/commandline/CliIT.java, Mustang-CLI/src/test/resources/cii.xml, library/pom.xml, validator/pom.xml
* as for module validation, creates an uber jar with classifier "shaded" besides the simple non-shaded jar
* the integration test for CLI assures that Cii2Ubl conversion is still working
=> solves #227

library/src/main/java/org/mustangproject/ZUGFeRD/OXExporterFromA3.java, library/src/main/java/org/mustangproject/ZUGFeRD/XMPSchemaPDFAExtensions.java, library/src/main/java/org/mustangproject/ZUGFeRD/XMPSchemaZugferd.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExporterFromA3.java
This represents a set of changes proposed from the Seeburger fork:
1. Allowing the XRechnung version to be explicitly set in the PDF meta-data (must match the version in the attached XML).
2. Change/fix for data relationship in case of MINIMUM and BASICWL profile. See documentation ZUGFeRD211_EN/Documentation/ZUGFeRD-2.1.1 - Specification_TA_Part-A.pdf
3. OrderX document type setting and slight meta-data improvements
4. Error handling improvements (exceptions not suppressed, throwing RutnimeException instead of error)
Maven build with the PR branch (including unit tests) works.
---------------------------------------------
BTW: I have seen one problem with the Mustang build. If the maven clean target is executed, the build overall fails. So
```
mvn clean package install  # will fail
mvn …
```
=> Multiple changes to do with XRechnung and OrderX

library/src/main/java/org/mustangproject/ZUGFeRD/OXPullProvider.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java
Someone always manages to insert a "&" in that node too ;-)
=> Add missing encodeXML to node payment terms description

library/src/main/java/org/mustangproject/ZUGFeRD/DXExporterFromA1.java, library/src/main/java/org/mustangproject/ZUGFeRD/DXExporterFromA3.java, library/src/main/java/org/mustangproject/ZUGFeRD/XMPSchemaPDFAExtensions.java
As of late 2022 the Delivery-X standard is not yet published. See specification:
Die digitale Ablösung des Papier-Lieferscheins, Version 1.1, April 2022 
Chapter 7.1 XMP-Erweiterungsschema für PDF/A-3
http://docplayer.org/230301085-Der-digitale-lieferschein-dls.html
Seeburger intends to deliver this as an early-access implementation, subject to change (when the standard is made official).
=> Proposed changes of namespace and meta-data for Delivery-X

.github/workflows/maven.yml, Mustang-CLI/pom.xml, library/pom.xml, pom.xml, validator/pom.xml
Hi Jochen,
as I have local test/build problems with Mustang on Linux and Windows with your recent commits, I thought it might make sense to pre-date your Xmas present and provide a black Friday pull request to you! :-)
This new Yaml file .github/workflows/maven.yml will trigger a build and tests using GitHub/Microsoft Cloud whenever a push is being made or a pull request is being offered to this project! \o/
I have chosen Ubuntu as the build platform and JDK 8 but you might add a matrix with multiple JDKs and platforms, see
- https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
- https://github.com/actions/setup-java#Usage 
Of course, it is a trojan horse as **before you can accept/merge my pull request**...
1. You have to fix your build :-) - …
=> Enabling Maven builds for push and pull requests in Github Cloud

Mustang-CLI/pom.xml, library/pom.xml, library/src/test/resources/junit-platform.properties, validator/pom.xml, validator/src/test/resources/junit-platform.properties
Hello Jochen,
as discussed, the easiest workaround for the following problem is to run "mvn package" or "mvn install" twice without a "mvn clean". 
First, I have added a dependency in the pom.xml of the validation module to the library module. So library will always be called before validation.
Second, as the library module requires executing the JUnit tests in alphabetical order, I have updated the JUnit dependency from 4 to 5 as this is possible in JUnit4 adding by adding a property JUnit file under test resources.
See https://stackoverflow.com/questions/57624495/junit-test-class-order
NOTE: You might want to consider migrating from 4 to 5 API - https://blog.jetbrains.com/idea/2020/08/migrating-from-junit-4-to-junit-5/  -> The clean JUnit 5 way would be exchanging the new two API and …
=> Module dependency update

library/pom.xml, validator/pom.xml
Exclude logback.xml in library and validator. Not in CLI.
Tested that the validator continues to generate log files.
=> Exclude logback.xml from final jar files

library/pom.xml, library/src/main/java/org/mustangproject/CII/CIIToUBL.java, library/src/test/java/org/mustangproject/ZUGFeRD/UBLTest.java, library/src/test/resources/ubl-conv-ubl-output-factur-x.xml
There is already version 2.0.1. Unfortunately the update results in many compatibility test failures and ClassNotFoundExceptions with to transitive dependencies. Therefore the step to 1.4.10 is sufficient for now.
Now without test failures.
=> Update helger library

Mustang-CLI/src/main/java/org/mustangproject/commandline/Main.java, Mustang-CLI/src/main/resources/logback.xml
Added new parameter "disable-file-logging" to disable logging to file.
=> new parameter "disable-file-logging" added

library/src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDTradeSettlementPayment.java
Hi, just noticed the `ram:SpecifiedTradeSettlementPaymentMeans` is missing its closing tag when the seller's BankDetails BIC number is left empty :-)
=> Missing closing tag in BankDetails when there's no BIC number

library/src/main/java/org/mustangproject/Charge.java, library/src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDAllowanceCharge.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDInvoiceImporter.java, library/src/test/java/org/mustangproject/ZUGFeRD/IZUGFeRDAllowanceChargeImpl.java
Added field reasonCode to IZUGFeRDAllowanceCharge, used for Charges and Allowances.
ZUGFeRDInvoiceImporter: read the value during import.
ZUGFeRD2PullProvider:
Export Allowances and Charges one by one, not aggregated by taxPercent, but only for profile XRechnung for now.
Don't know if this is also allowed for other profiles also.
Added reasonCode also on item level.
Removed some obsolete spaces in xml-Fragments.
=> Enhance Charges/Allowances with reasonCode.

Mustang-CLI/pom.xml, library/pom.xml, pom.xml, validator/pom.xml
Change pom.xml files to get rid of warnings when editing them in Eclipse and running maven install.
**From Eclipse:**
```
Description	Resource	Path	Location	Type
Invalid plugin configuration: encoding	pom.xml	/core	line 95	Language Servers
Description	Resource	Path	Location	Type
GroupId is duplicate of parent groupId	pom.xml	/library	line 11	Language Servers
Invalid plugin configuration: descriptorRefs	pom.xml	/library	line 173	Language Servers
Version is duplicate of parent version	pom.xml	/library	line 13	Language Servers
Description	Resource	Path	Location	Type
GroupId is duplicate of parent groupId	pom.xml	/validator	line 9	Language Servers
Invalid plugin configuration: descriptorRefs	pom.xml	/validator	line 137	Language Servers
Version is duplicate of parent version	pom.xml	/validator …
```
=> Fix build warnings from editing and building.

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDVisualizer.java
PDF/A-1b doesn't support embedded files, but when converting e.g. an XRechnung with an attached document, the visualizer tries (and fails) to attach it to the generated PDF.
This diff just changes the PDF generation to PDF/1-3b.
=> ZUGFeRDVisualizer.toPDF(): generate PDF/A-3b.

library/src/main/java/org/mustangproject/DirectDebit.java, library/src/main/java/org/mustangproject/Invoice.java, library/src/main/java/org/mustangproject/TradeParty.java, library/src/main/java/org/mustangproject/ZUGFeRD/IExportableTransaction.java, library/src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDTradeSettlementDebit.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java
Related to #436 and #370.
```
<ram:ApplicableHeaderTradeSettlement>
<ram:CreditorReferenceID>DE88ZZZ00000032626</ram:CreditorReferenceID>
```
```
<ram:SpecifiedTradeSettlementPaymentMeans>
<ram:TypeCode>59</ram:TypeCode>
<ram:Information>SEPA direct debit</ram:Information>
<ram:PayerPartyDebtorFinancialAccount>
<ram:IBANID>DE35403616270001668600</ram:IBANID>
</ram:PayerPartyDebtorFinancialAccount>
</ram:SpecifiedTradeSettlementPaymentMeans>
```
```
<ram:SpecifiedTradePaymentTerms>
<ram:Description>...</ram:Description>
<ram:DirectDebitMandateID>4711</ram:DirectDebitMandateID>
</ram:SpecifiedTradePaymentTerms>
```
=> Direct Debit: add field CreditorReferenceID.

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDVisualizer.java
Verwendet in `ZUGFeRDVisualizer.toPDF` die bereits instanziierte `ZUGFeRDVisualizer`-Klasse, statt eine neue Instanz zu erzeugen. Hierdurch müssen die in [ZUGFeRDVisualizer.java#L97-L101](https://github.com/matmen/mustangproject/blob/e2ff39e10f0341392af3accab202c666a83d04c7/library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDVisualizer.java#L97-L101) definierten Variablen nicht erneut eingelesen bzw. die XSLT-Templates nicht neu geparsed werden. In meinen Benchmarks (10 Iterationen Warmup, 100 Iterationen Test) kann das ca. 80% Rechenleistung (wall time, vorher ~840ms/op, danach ~160ms/op) einsparen, sofern eine "globale" Instanz wiederverwendet wird.
Außerdem wird ein m.M.n. ungenutzes Dateilesen entfernt.
Bislang konnte ich bei meinen Tests noch keine side-effects erkennen.
=> refactor(ZUGFeRDVisualizer): improve PDF visualization performance

library/src/main/java/org/mustangproject/TradeParty.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDInvoiceImporter.java, library/src/test/java/org/mustangproject/ZUGFeRD/ZF2PushTest.java
Read missing Invoice fields
TradeParty.ID
ExchangedDocument.TypeCode
ApplicableHeaderTradeDelivery.DespatchAdviceReferencedDocument.IssuerAssignedID
Everything else is reformatting, joining split lines together for, in my opinion, better readability.
Enhance ZF2PushTest to check the now filled fields.
Formatting and changing some assertEquals to set the expected value as the first parameter.
=> Read missing fields for imported Invoice.

library/src/main/java/org/mustangproject/Charge.java
Makes the usage of getTotalAmount clearer because you can choose if you want the total amount of the charge of of an item with the percentage of the item.
Maybe also rename
`public BigDecimal getTotalAmount(IAbsoluteValueProvider currentItem)`
to
`public BigDecimal getItemAmount(IAbsoluteValueProvider currentItem)`
=> Makes the getTotalAmount() function easier to use

Mustang-CLI/src/main/java/org/mustangproject/commandline/Main.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExporterFromPDFA.java
Related to #448 .
Moved adding of Attachments after loading the pdf-file. Only at this point it's clear, of which type the source pdf is.
Check if exporter class is really of type ZUGFeRDExporterFromA3, else (ZUGFeRDExporterFromA1) print an error message.
At least with a source pdf of PDF/A-3A it works.
Class ZUGFeRDExporterFromA1 does not support Attachments, because in PDF/A-1 (ISO 19005-01) version 1.4 (2005) Attachments are NOT allowed.
```
java -jar Mustang-CLI-2.13.0-SNAPSHOT.jar --action combine --source Rechnung.pdf --source-xml CII-XRechnung-4711-0815-xml.xml --out ZF_Rechnung.pdf --format zf --version 2 --profile E  --attachments "CII-XRechnung-4711-0815-xml.pdf"
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See …
```
=> Fix ClassCastException in CLI (Main.java).

library/src/main/java/org/mustangproject/Item.java, library/src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDExportableItem.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD1PullProvider.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java
Wir stehen vor der Herausforderung Sammelrechnungen abbilden zu müssen. Hierzu ist es erforderlich je Rechnungsposition eine Liste von Details (u.a. Vertragsnummer) zu hinterlegen, damit der Rechnungsempfänger die Position korrekt zuordnen kann.
Nach eingehender Betrachtung der ZUGFeRD Dokumentation sind wir zu dem Schluss gekommen, dass die positionsbezogenen Referenzen in BT-128 zu hinterlegen sind. Dies entspricht dem Pfad CrossIndustryInvoice / SupplyChainTradeTransaction / IncludedSupplyChainTradeLineItem / SpecifiedLineTradeSettlement / AdditionalReferencedDocument, welcher in ZF2 als Liste mehrerer Referenzen vorgesehen ist.
Bisher ist von mustangproject hierfür nur ein String vorgesehen gewesen (IZUGFeRDExportableItem.getAdditionalReferencedDocumentID), welcher allerdings nur im …
=> changed additional references by line from String to List and implemented it on Item

Mustang-CLI/pom.xml, library/pom.xml, pom.xml, validator/pom.xml
This PR includes a refactoring of the project POMs.
- Formatted all POMs using Maven sortpom Plugin
- Removed duplicated configuration (will be inherited from the parent POM)
- Moved all plugins to plugin management with a base (default) configuration
- Use plugins in modules by referencing them, added additional configuration if needed
- Updated plugin versions
- Add test-jar to created jars on build (I wonder why Maven Central did not complain about that)
- Moved common dependencies to dependency-management
- Added properties for all used dependency versions
- this allows defining the versions only once and at a well defined position
I build everything locally and also did `release:prepare` and `release:perform`. 
The created artifacts looks good to me. POM seems to be complete (not …
=> Re-Formatted and re-organized POMs

library/src/main/java/org/mustangproject/Invoice.java, library/src/main/java/org/mustangproject/ZUGFeRD/IExportableTransaction.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDInvoiceImporter.java, library/src/test/java/org/mustangproject/ZUGFeRD/XRTest.java, library/src/test/java/org/mustangproject/ZUGFeRD/ZF2ZInvoiceImporterTest.java, library/src/test/resources/testout-ZF2new.ubl.xml
Some of our customers use Factoring, for an explanation see https://en.wikipedia.org/wiki/Factoring_(finance).
So the receiver of the payment for this invoice is not the Seller but a third party organization.
For this
- added payee TradeParty to the Invoice class
- add it's serialization into ZUGFeRD2PullProvider class, it has a very limited list of fields
- add deserialization to ZUGFeRDInvoiceImporter class for CII and UBL
- enhance tests to make sure, it get's written and read, CII and UBL
=> Enable suport for PayeeTradeParty / PayeeParty.

library/src/test/java/org/mustangproject/ZUGFeRD/ZF2PushTest.java
The test writes `TARGET_ATTACHMENTSPDF` but validates `TARGET_PDF`. This fails twice:
- on a clean build when reading the file because it does not (yet) exist
- on subsequent builds because the file content is not the expected content
=> Fix test using wrong file

validator/pom.xml
Without these dependencies the `validator` project cannot be build. The build still fails due to a validation error in a test, though.
```
[INFO] --- compiler:2.3.2:compile (default-compile) @ validator ---
[INFO] Compiling 10 source files to /Users/jan/git/mustangproject/validator/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/jan/git/mustangproject/validator/src/main/java/org/mustangproject/validator/ZUGFeRDValidator.java:[23,28] error: package org.apache.commons.io does not exist
[ERROR] /Users/jan/git/mustangproject/validator/src/main/java/org/mustangproject/validator/ZUGFeRDValidator.java:[24,16] error: package org.dom4j does not exist …
```
=> Fix validator dependencies

validator/src/main/java/org/mustangproject/validator/XMLValidator.java, validator/src/test/java/org/mustangproject/validator/XMLValidatorTest.java, validator/src/test/resources/invalidXRSchemav2.xml
Add a test case with an invalid XR (elements in wrong order).
=> Enable EN16931 schema validation for XRechnung.

library/src/main/java/org/mustangproject/LegalOrganisation.java
The id and scheme id are reversed in the constructor of `LegalOrganisation` when creating the `SchemedId`.
=> Fix LegalOrganisation schemeId

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java
Fixes #412 
The default implementation of `IExportableTransaction`(which is `Invoice`) always returns an `ArrayList` when calling `getNotesWithSubjectCode()`, however the interface only requires a `List` which could also be unmodifiable or immutable. If such a collection is returned the `buildNotes` method on the `ZUGFeRD2PullProvider` throws an UOE when trying to add more notes to the collection.
=> Fix UnsupportedOperationException in buildNotes

library/src/main/java/org/mustangproject/Product.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java
TaxCategory ws null now at a couple of tests.
Fall back to the default implementation in the interface to fill the gap.
Open failures then:
```
[ERROR]   LibraryTest.testMinimumProfileValidityCreditNote:280 [XPath "count(//error)" evaluated to value] expected:<[0]> but was:<[1]>
[ERROR]   LibraryTest.testMinimumProfileValidityInvoice:256 [XPath "count(//error)" evaluated to value] expected:<[0]> but was:<[1]>
```
```
<messages>
<error type="4" location="/*[local-name()='CrossIndustryInvoice']/*[local-name()='SupplyChainTradeTransaction']/*[local-name()='ApplicableHeaderTradeAgreement']/*[local-name()='BuyerTradeParty']/*[local-name()='SpecifiedLegalOrganization']/*[local-name()='ID']" criterion="document('FACTUR-X_MINIMUM_codedb.xml')//cl[@id=5]/enumeration[@value=$codeValue5]">Value of …
```
=> Fix current validation errors.

Mustang-CLI/pom.xml
Fixes #434 
No logging implementation was included in the shaded jar resulting in the mentioned error message and missing log outputs.
=> Fix logging implementation missing in CLI

library/src/main/resources/stylesheets/xr-content.xsl
Change layout for Informationen zum Vertrag layout to display information on single column to prevent long text overlay.
Closes #499
=> Update xr-content.xsl - fix #499

library/pom.xml
Fixes #422 
Fixes #505 
This is the result of the reduced POM generation by the maven-shade-plugin. Some unnecessary configuration was clean up, too.
This also re-orders the dependencies so that the `test` dependencies are grouped at the end and all others before.
=> Fix POM missing dependencies

validator/src/main/java/org/mustangproject/validator/PDFValidator.java
Note: Searching on the whole file contents for a specific siganture string can be unsuccessful. E.g. info dictionary can be missing and XMP data can be compressed. Beginning with PDF 2.0 info dictionaries became also deprecated.
=> Add CIB pdf brewer signature

validator/src/test/java/org/mustangproject/validator/XMLValidatorTest.java, validator/src/test/resources/CII_XRechnung_with_Peppol_violation.xml
XMLValidation was not supporting warnings. Because of this severity warning rule violations failed validation with error.
This adds a test verifying that #546 has been fixed
=> Add test verifying #546 has been fixed

validator/src/main/java/org/mustangproject/validator/XMLValidator.java, validator/src/test/java/org/mustangproject/validator/ZUGFeRDValidatorTest.java
In org.mustangproject.validator.XMLValidator.validateSchematron(), the severity has to be determined for every node of the validation result.  Otherwise, all schematron assertions tagged as "fatal" will be treated as warnings after the first warning.
=> Treat all fatal XR schematron rules as errors, not as warnings.

library/pom.xml, validator/pom.xml
Refers to https://github.com/ZUGFeRD/mustangproject/issues/574.
For more see
https://stackoverflow.com/questions/57286825/the-package-org-w3c-dom-is-accessible-from-more-than-one-module-unnamed-java
also.
=> dom4j: exclude all (optional) dependencies to avoid potential conflicts.

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExporterFromPDFA.java
In ZUGFeRDExporterFromPDFA, the open filestream was not safely closed when the load(String) function was called.
=> Fixes a problem where a stream was not safely closed

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java
Fix issue #296 (duplicate of #565) in ZUGFeRD2PullProvider: DueDate must appear before the mandate ID in the XML.
=> Fix issue #296 (duplicate of #565) in ZUGFeRD2PullProvider

library/src/main/resources/stylesheets/result-pdf.xsl
The case that no messages exist has already been fixed (cf. #645).
- Unfortunately, there are some other corner cases: The script [result-pdf.xsl](library/src/main/resources/result-pdf.xsl) does consider notices and errors only, it does not consider warnings yet. Therefore, it fails if only warnings exist.
- Furthermore, the document type can become quite long. Examples:
> urn:cen.eu:en16931:2017
> urn:cen.eu:en16931:2017#compliant#urn:factur-x.eu:1p0:basic
> urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0
> urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0
> urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0#conformant#urn:xeinkauf.de:kosit:extension:xrechnung_3.0
> …
=> Fix log visualization

library/src/main/java/org/mustangproject/Invoice.java, library/src/main/java/org/mustangproject/ZUGFeRD/IExportableTransaction.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDInvoiceImporter.java, library/src/test/java/org/mustangproject/ZUGFeRD/ZF2PushTest.java
The value for the PaymentRefrence was always the Invoice number. Make it settable by the user.
Business case: Payment reference should also contain the invoice date and the customer id, not only the number.
Add DocumentName for the Extended-Profile only. See #605.
Enhance a test to check the values.
=> Enable flexible PaymentReference and a DocumentName.

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDInvoiceImporter.java
This allows to distinguish between UBL's Invoice and UBL's CreditNote. I think this is usefule, since further processing with UBL libraries requires knowledge about the document type.
=> Fix #632: Return ubl_creditnote as Standard for CreditNotes

validator/pom.xml
Hello,
I noticed today that the validator includes VeraPDF in the version 1.26.1. However, there is a vulnerability tracked under [CVE-2024-52800](https://nvd.nist.gov/vuln/detail/CVE-2024-52800) for this version of VeraPDF. Luckily, this was addressed by the VeraPDF authors and fixed in version 1.26.2 (see https://github.com/veraPDF/veraPDF-library/releases/tag/v1.26.5 ). I think it would be a good thing, if we upgraded that dependency too.
I've upgraded the VeraPDF dependency to 1.26.2 and ran all tests locally, which passed.
Kind Regards,
Fatih
=> Upgrades VeraPDF dependency to version 1.26.2

library/src/test/java/org/mustangproject/ZUGFeRD/DeSerializationTest.java, library/src/test/java/org/mustangproject/ZUGFeRD/ZF2ZInvoiceImporterTest.java
Fix current failures.
JSON-Datetime with timezone gets deserialized using the current timezone.
I have set TZ to Europe/Berlin , there the test worked.
Githup possiby is using American timezone, so the date only part gets shifted to the previous day.
Removing the timezone on ohne of the datetime values is sufficient, because contains("<udt:DateTimeString format=\"102\">20180304</udt:DateTimeString>") is used. One date with this value is sufficient.
testImportDebit uses cii/minimalDebit.xml containing TypeCode 59 / DirectDebit.
So the Recipient gets the BankDetails assigned (library/src/test/java/org/mustangproject/ZUGFeRD/ZF2ZInvoiceImporterTest.java#816).
Due to the additional charge in library/src/test/java/org/mustangproject/ZUGFeRD/ZF2PushTest.java, testItemChargesAllowancesExport the …
=> Fix current check failures.

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDInvoiceImporter.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDVisualizer.java, library/src/test/java/org/mustangproject/ZUGFeRD/VisualizationTest.java, validator/src/main/java/org/mustangproject/validator/XMLValidator.java, validator/src/main/java/org/mustangproject/validator/ZUGFeRDValidator.java
XML parsers should not be vulnerable to XXE attacks
Reference to https://github.com/ZUGFeRD/mustangproject/issues/685
=> Unable to perform XML-oriented attacks

library/src/main/java/org/mustangproject/ZUGFeRD/ValidationLogVisualizer.java
Reuse toPDF method to work without any dependencies to the file system for ValidationLogVisualizer as we also do at ZUGFeRDVisualizer https://github.com/ZUGFeRD/mustangproject/pull/649
//Recreated PR cause of new branch
=> extend ValidationLogVisualizer to not use only file system

library/src/main/resources/stylesheets/xr-mapping.xsl, library/src/main/resources/stylesheets/xrechnung-html.de.ids.xsl, library/src/main/resources/stylesheets/xrechnung-html.de.xsl, library/src/main/resources/stylesheets/xrechnung-html.xsl, library/src/test/resources/factur-x-vis-extended.de.html
For "Postfach" instead of "Straße / Hausnummer" Adresszusatz 1 should be used filled with fixed text "Postfach" followed by the number.
_XRG-20 (Erste Adresszeile einheitlich erläutern): In den Beschreibungen zu BT-35 und BT-64 wurde der Hinweis „Üblicherweise ist dies entweder Strasse und Hausnummer oder der Text ‚Postfach‘ gefolgt von der Postfachnummer.“ ergänzt, der bei anderen Elementen, die Adressen beschreiben (z.B. BT-50), bereits vorhanden war._
#742
=> Do not output "Adresszusatz 1" as "Postfach".

library/src/main/java/org/mustangproject/Invoice.java
The setCorrection function in the Invoice class uses the old setInvoiceReferencedDocumentID function and the new addInvoiceReferencedDocument function. This results in a duplicate output of InvoiceReferencedDocument in the XML. As the name setCorrection does not indicate that the function works additively, the call to addInvoiceReferencedDocument has been removed.
=> Invoice setCorrection causes duplicate XML output

Mustang-CLI/src/main/java/org/mustangproject/commandline/Main.java, library/src/main/java/org/mustangproject/XMLTools.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExporterFromPDFA.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDInvoiceImporter.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDVisualizer.java, validator/src/main/java/org/mustangproject/validator/ZUGFeRDValidator.java
**Main.java:** Proper closing of the InputStream in the method convertInputStreamToString
**ZUGFeRDExporterFromPDFA.java:** Closing of the DataInputStream
**ZUGFeRDInvoiceImporter.java:** Closing of the InputStream for XMP metadata
**ZUGFeRDValidator.java:** Explicit closing of the XMLWriter
**ZUGFeRDVisualizer.java:** Proper closing of the FileInputStream
=> Fix potential resource leaks in core file processing classes

validator/src/main/java/org/mustangproject/validator/PDFValidator.java
I've added ZUGFeRD.PDF-csharp to the list of valid PDF creators. The only complaint left when validating PDFs that were created with ZUGFeRD.PDF-csharp :)
=> Added ZUGFeRD.PDF-csharp to list of valid PDF creators

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDImporter.java
This PR fixes the following error especially when trying to import the _ZUGFeRD v1_ invoice with buyer trade party address section.
```
ERROR [org.mus.ZUG.ZUGFeRDImporter] (executor-thread-1) Failed to evaluate XPath: javax.xml.xpath.XPathExpressionException: javax.xml.transform.TransformerException: Could not find function: localname
at java.xml/com.sun.org.apache.xpath.internal.jaxp.XPathImpl.compile(XPathImpl.java:174)
at org.mustangproject.ZUGFeRD.ZUGFeRDImporter.getNodeListByPath(ZUGFeRDImporter.java:854)
at org.mustangproject.ZUGFeRD.ZUGFeRDImporter.getBuyerTradePartyAddress(ZUGFeRDImporter.java:530)
```
=> Fix typo in xpath when extracting buyer trade party address

library/src/main/resources/stylesheets/result-pdf.xsl
Problem:
If a Validation Result XML ([validationReport.txt](https://github.com/user-attachments/files/19905909/validationReport.txt)) is transformed to an PDF using ValidationLogVisualizer the output of the PDF is following:
Solution:
Changes in xlst-transformation file with help of "IntersperseWithZeroSpaces" to wrap the message and display all characters.
=> Wrapping Message Text in Validation Result PDF

library/src/main/java/org/mustangproject/ZUGFeRD/VATAmount.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java, library/src/main/java/org/mustangproject/ZUGFeRD/model/TaxCategoryCodeTypeConstants.java, library/src/test/java/org/mustangproject/ZUGFeRD/XRTest.java
Problem:
1. Create an invoice where products have category code "O", add an allowance or charge (with the same exemption code).
2. Add exemption reason to the products, allowance/charges don't have a field for exemption reason
3. Validate the generated XML with the Mustang validator
Errors:
1. A Document level charge (BG-21) where the VAT category code (BT-102) is "Not subject to VAT" shall not contain a Document level charge VAT rate (BT-103).
2. [BR-O-10]-A VAT Breakdown (BG-23) with VAT Category code (BT-118) " Not subject to VAT" shall have a VAT exemption reason code (BT-121), meaning " Not subject to VAT" or a VAT exemption reason text (BT-120) " Not subject to VAT" (or the equivalent standard text in another language).
To fix the first error, i made the RateApplicablePercent …
=> Fix Invoices with Category Code "O"

library/src/main/java/org/mustangproject/BankDetails.java, library/src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDTradeSettlementPayment.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java
This pull request introduces two new changes:
- Addition of the tag `/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:SpecifiedTradeSettlementHeaderMonetarySummation/ram:LineTotalAmount` which must be present in the BASICWL profile according to the Factur-X v1.07.2 standard.
- Possibility of setting a code other than 58 in the `/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:SpecifiedTradeSettlementPaymentMeans/ram:TypeCode` tag. The Factur-X v1.07.2 standard allows codes other than this one. In particular, when transferring Factur-X to ChorusPro. Chorus Pro is a French government platform for invoice transmission. For example, the platform only accepts code 30 for SEPA transfers.
I hope …
=> Updates about SpecifiedTradeSettlementHeaderMonetarySummation and SpecifiedTradeSettlementPaymentMeans

library/src/main/resources/stylesheets/l10n/de.xml, library/src/main/resources/stylesheets/ubl-creditnote-xr.xsl, library/src/main/resources/stylesheets/ubl-invoice-xr.xsl, library/src/main/resources/stylesheets/xr-content.xsl, library/src/test/resources/factur-x-vis-ubl.en.html
=> Got a broken translation key when visualizing XML into PDF (xr:Business_process_type)

validator/src/main/java/org/mustangproject/validator/PDFValidator.java
Sevdesk can be used to create ZUGFeRD invoices. In order to get the sevdesk signature listed in the PDFvalidator I added it to the list of valid creators.
=> Add sevdesk signature to valid PDF creators

Mustang-CLI/src/main/java/org/mustangproject/commandline/Main.java
With this change, the extract processs is quiet.
```
$ java -jar Mustang-CLI/target/Mustang-CLI-2.17.0-SNAPSHOT.jar --action extract --source *.pdf
Source PDF set to Rechnung_50006.1.pdf
ZUGFeRD XML (default: factur-x.xml):
Written to factur-x.xml
```
=> Ignore calculation errors when extracting xml from pdf.

library/src/main/java/org/mustangproject/Item.java, library/src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDExportableItem.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java, library/src/test/java/org/mustangproject/ZUGFeRD/UBLTest.java, library/src/test/java/org/mustangproject/ZUGFeRD/ZF2PushTest.java
=> Add support for BuyerOrderReferencedDocument on line level

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDInvoiceImporter.java
We encountered a NullPointerException when processing certain PDFs. After investigating, we identified the root cause: node.getNames() can return null, which was not previously accounted for.
This PR adds a null check to safely handle this edge case.
=> Skip PDNameTreeNodes if the names are null or empty

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDInvoiceImporter.java, validator/src/test/java/org/mustangproject/validator/ResourceCase.java
`PDDocument` implements the `AutoClosable` interface and therefore can be closed automatically with the try-with-resources mechanism.
=> Close resources after usage

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDInvoiceImporter.java
In some cases the dates in ZUGFeRD documents contains a unsupported format (`610`) with pattern `yyyyMM`.
Mustang did throw a `ParseException` and stopped the whole XML parsing.
With this change the unparsable dates are set to `NULL` if there is a problem with the format.
In addition the date parsing is moved to method that handles the parsing.
=> Parsing exceptions of date strings does not break XML parsing

validator/src/main/java/org/mustangproject/validator/XMLValidator.java, validator/src/test/java/org/mustangproject/validator/ZUGFeRDValidatorTest.java, validator/src/test/resources/validXRV30.xml
XRechnung 3.0.3 Summer 2025 edition introduced a rule with flag="information", breaking the Mustangproject validator which doesn't expect such a flag value.
See
https://projekte.kosit.org/xrechnung/xrechnung-schematron/-/commit/06be5b2c75f79a5f5e2f5156a34117f60f1fe099
Explicitly mapping "information" to ESeverity.notice hopefully fixes this and any future additions of rules with flag="information".
=> Treat schematron rule flag "information" as notice.
