ZUGFeRD/mustangproject

pom.xml, src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExporter.java, src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExporterFromA1Factory.java, src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDTransactionModelConverter.java, src/test/java/org/mustangproject/ZUGFeRD/MustangReaderWriterEdgeTest.java, src/test/java/org/mustangproject/ZUGFeRD/MustangReaderWriterTest.java
=> Fix compilation errors mainly due to merge conflicts

src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDTransactionModelConverter.java
=> Remove hardcoded prefix "Ursprungsbeleg: " from reference info

src/main/java/org/mustangproject/ZUGFeRD/VATAmount.java, src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDTransactionModelConverter.java
pull request for #95.
passes tests and produces expected category code in XML file
=> deprecate misleading documentCode in favour of categoryCode

src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java
re #101 
* omit SpecifiedTaxRegistration if VATID is null
* use IncludedNote instead of IncludedCINote
=> updates for 2.0 compatibility (IncludedNote, SpecifiedTaxRegistration)

src/test/java/org/mustangproject/ZUGFeRD/MustangReaderWriterCustomXMLTest.java, src/test/java/org/mustangproject/ZUGFeRD/MustangReaderWriterEdgeTest.java, src/test/java/org/mustangproject/ZUGFeRD/MustangReaderWriterTest.java, src/test/java/org/mustangproject/ZUGFeRD/ResourceUtilities.java, src/test/java/org/mustangproject/ZUGFeRD/VersionMigrationTest.java, src/test/java/org/mustangproject/ZUGFeRD/ZF2EdgeTest.java
Re #24: IntelliJ now succeeds in building javadoc
Further improvements possible
=> iron out javadoc errors and warnings

src/main/java/org/mustangproject/ZUGFeRD/model/DocumentContextParameterTypeConstants.java
see "Das ZUGFeRD-Format_1p0", p. 98, lines 1982 ff.
=> complete profile options for v1

src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDExportableTransaction.java, src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDTransactionModelConverter.java
=> make BuyerOrderReferencedDocument accessible

src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDExportableTransaction.java, src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDTransactionModelConverter.java
This is a manually tested implementation for #118.
Updating the existing tests seems to be ... troublesome.
=> Implement TotalPrepaidAmount

src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java
=> use totalPrepaidAmount to calculate duePayableAmount (for v2)

src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java
=> add missing ram: to closing tag

src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDImporter.java
I noticed that `getDocument` parses the contents of `rawXML` for each invocation of `extractString`.
Here I'm using a setter for rawXML to parse `rawXML` once after changing its value so that `getConfig` can now return this prepared Document. Current unit tests pass and even run a tiiiiny bit faster than before.
=> parse rawXML into document only once

src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDImporter.java
edit some comments, add some more, move related methods together
=> comment editing and cosmetic improvements

src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDExportableTransaction.java, src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDTransactionModelConverter.java
removed @getBuyerOrderReferencedDocument: not used after merge; only call
@setIssueDateTime if not null to avoid tag with NULL value
Thanks for merging my changes. i did some changes after merge for clean up
=> removed unsed Methode; IssuedDateTime only if not null

src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExporter.java
this is the trivial change for #73
=> switch to ZUGFeRD v2 as DefaultZUGFeRDVersion

libraryBasic/src/main/java/org/mustangproject/ZUGFeRD/Item.java, libraryBasic/src/main/java/org/mustangproject/ZUGFeRD/VATAmount.java, libraryBasic/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDImporter.java, libraryBasic/src/test/java/org/mustangproject/ZUGFeRD/ZF2Test.java
Added functions for extracting LineItems and modified some existing extractions functions to match ZUGFeRD 1.x and ZUGFeRD 2.x
=> Add extraction methods

library/src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDExportableItem.java, library/src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDExportableProduct.java, library/src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDExportableTransaction.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java, library/src/test/java/org/mustangproject/ZUGFeRD/ZF2ZInvoiceImporterTest.java
Various bugfixes and handling of some additional properties when generating the XML during export.
=> Bugfixes and new export props

library/src/main/java/org/mustangproject/ZUGFeRD/TransactionCalculator.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD1PullProvider.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java
Use TaxCategoryCode instead of DocumentCode by creating VATPercentAmountMap. #186
=> Correct tax category code

library/src/main/java/org/mustangproject/ZUGFeRD/XRechnungImporter.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDImporter.java
Just another importer to import an XRechnung in xml
=> XRechnung importer

doc/MustangWriter.java
This fixes the compile errors that came up after trying to use the sample file.
Now it compiles fine and produces ZF2
Most likely, other changes have to be done.
=> Update sample MustangWriter for Mustangproject 2.0.2

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDImporter.java
Otherwise the buyerTradePartyAddress is not found.
=> Remove faulty '/' from getNodeListByPath call.

Mustang-CLI/pom.xml, Mustang-CLI/src/main/resources/logback.xml
by setting system property "disable-file-logging" , e.g.:
`java -Ddisable-file-logging=true -jar Mustang-CLI.jar --action ...`
=> fixes #259: disable file logging 

Mustang-CLI/src/main/java/org/mustangproject/commandline/Main.java
Also in this PR:
- Making the --attachment option operational
- Renaming --attachment to --attachments
- Adding the "ox" format to the usage output
Please note that specifying an empty string for the --attachments option is the way to prevent the program from prompting for attachments. That perhaps is a bit clunky but I don't have a better idea. 
Something else, I noticed lines like this:
```Java
Boolean filesFromStdIn = cmd.hasOption("listfromstdin");
```
The signature of the called function however is (See here: https://commons.apache.org/proper/commons-cli/javadocs/api-release/org/apache/commons/cli/CommandLine.html#hasOption-java.lang.String-):
```Java
public boolean hasOption(String)
```
Any reason for this?
=> Fixed issue that specifying an attachment was mandatory (issue #270)

library/src/main/java/org/mustangproject/Invoice.java, library/src/main/java/org/mustangproject/TradeParty.java, library/src/main/java/org/mustangproject/ZUGFeRD/IExportableTransaction.java, library/src/main/java/org/mustangproject/ZUGFeRD/LineCalculator.java, library/src/main/java/org/mustangproject/ZUGFeRD/TransactionCalculator.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD1PullProvider.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDImporter.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDInvoiceImporter.java
This pull request contains some adjustments for importing ZUGFeRD 1 invoices.
=> ZUGFeRD 1 Import

library/pom.xml
Allow to bundle the library jar without all the dependencies and to use it in another application.
see https://github.com/ZUGFeRD/mustangproject/issues/262#issuecomment-1110062727
=> issue 262 - bundle library jar without all dependencies

library/src/main/java/org/mustangproject/XMLTools.java
Maybe a null check before calling this method is the better way to prevent this exception? But in my opinion it is good enough.
=> Prevent NPE

Mustang-CLI/src/test/java/org/mustangproject/commandline/CliIT.java, library/pom.xml, validator/pom.xml, validator/src/main/java/org/mustangproject/validator/PDFValidator.java
This does not already solve the problem of using a valid PDF/A-3b file, but it is a step in the correct direction...
=> Updating versions of VeraPDF and PDFBox

library/src/main/java/org/mustangproject/Invoice.java, library/src/main/java/org/mustangproject/ZUGFeRD/IExportableTransaction.java, library/src/main/java/org/mustangproject/ZUGFeRD/TransactionCalculator.java, library/src/main/java/org/mustangproject/ZUGFeRD/VATAmount.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD1PullProvider.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java, library/src/main/java/org/mustangproject/ZUGFeRD/model/EventTimeCodeTypeConstants.java, library/src/test/java/org/mustangproject/ZUGFeRD/ZF2PushTest.java
PR for issue #308 
Hi, I had some spare time to work on the VAT due date collection (see issue). It works fine for my use case but I'm not sure I have the necessary broad vision of the project to say it will be the case for everyone. Any input on this problem is very much welcomed :)
=> Issue 308: define when VAT collection become applicable

library/src/main/java/org/mustangproject/IncludedNote.java, library/src/main/java/org/mustangproject/Invoice.java, library/src/main/java/org/mustangproject/SubjectCode.java, library/src/main/java/org/mustangproject/ZUGFeRD/DAPullProvider.java, library/src/main/java/org/mustangproject/ZUGFeRD/IExportableTransaction.java, library/src/main/java/org/mustangproject/ZUGFeRD/OXPullProvider.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java
There is the possibility now to add notes with specific subject code (the recommended ones from the specification).
Some refactorings were done
=> Improvement of included notes

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDImporter.java
=> Added XRechnung Profile support

validator/src/main/java/org/mustangproject/validator/PDFValidator.java, validator/src/main/java/org/mustangproject/validator/Validator.java, validator/src/main/java/org/mustangproject/validator/XMLValidator.java, validator/src/main/java/org/mustangproject/validator/ZUGFeRDValidator.java
Autoload needs to be checked in both the XMLValidator and the Pdf Validator.
=> Moved Autoload to validator

library/src/main/java/org/mustangproject/ZUGFeRD/UBLDAPullProvider.java, library/src/main/java/org/mustangproject/ZUGFeRD/XRechnungImporter.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD1PullProvider.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDImporter.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDVisualizer.java, library/src/test/java/org/mustangproject/ZUGFeRD/CalculationTest.java, library/src/test/java/org/mustangproject/ZUGFeRD/ResourceUtilities.java
* Replace all occurrances of java.util.logging stuff with SLF4J
* Added initial messages instead of "null" loggings
* Remove double logging, where it was evident that it does not add value
=> Replace java.util Logging with SLF4J

library/src/main/java/org/mustangproject/Product.java, library/src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDExportableProduct.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java
Adds ApplicableProductCharacteristic (BG-32:BT-160/BT-161) and OriginTradeCountry (BT-159) to Product.
Refers to #420.
=> Add ApplicableProductCharacteristic and OriginTradeCountry to Product. #420.

library/src/main/java/org/mustangproject/Item.java
/rsm:CrossIndustryInvoice/
rsm:SupplyChainTradeTransaction/
ram:IncludedSupplyChainTradeLineItem/
ram:SpecifiedLineTradeAgreement/
ram:BuyerOrderReferencedDocument/ram:LineID
=> Read Item.referencedLineID.

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java
=> Avoid NullPointerException if dueDate is not set.

library/src/test/java/org/mustangproject/ZUGFeRD/CalculationTest.java
Set the ReasonCode (BT-98 / BT-105) of allowances and charges, not the CategoryCode, (BT-95 / BT-102) 
Set a value > 0 for item_increase here and there, so that also Charges get added on item and on invoice level.
Adjust the expected value for the GrandTotal.
=> Adjust CalculationTest.java.

library/src/main/java/org/mustangproject/ZUGFeRD/TransactionCalculator.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDInvoiceImporter.java, library/src/test/java/org/mustangproject/ZUGFeRD/UBLTest.java, library/src/test/resources/ubl/04.01a-INVOICE_ubl.xml
=> Fix prepaid amount in importer

library/src/main/java/org/mustangproject/TradeParty.java, library/src/test/java/org/mustangproject/ZUGFeRD/DeSerializationTest.java
* email serialization was working
* add verification to test
* remove redundant UriUniversalCommunicationID and UriUniversalCommunicationScheme
=> closes #456

library/src/main/java/org/mustangproject/ClassCode.java, library/src/main/java/org/mustangproject/DesignatedProductClassification.java, library/src/main/java/org/mustangproject/Item.java, library/src/main/java/org/mustangproject/Product.java, library/src/main/java/org/mustangproject/ReferencedDocument.java, library/src/main/java/org/mustangproject/SchemedID.java, library/src/main/java/org/mustangproject/XMLTools.java, library/src/main/java/org/mustangproject/ZUGFeRD/IDesignatedProductClassification.java, library/src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDExportableProduct.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java, library/src/main/java/org/mustangproject/util/NodeMap.java
Also contains refactoring of the XML parsing for the `Item` class.
=> Add DesignatedProductClassification for SpecifiedTradeProduct

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDInvoiceImporter.java
A format has gone over this file - if you're not happy with it, I'll revert the changes
Fixes #525
=> Trim values of whitespace before parsing

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDImporter.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDInvoiceImporter.java, library/src/test/java/org/mustangproject/ZUGFeRD/VisualizationTest.java, library/src/test/java/org/mustangproject/ZUGFeRD/ZF2PushTest.java
Add attribute @Deprecated where needed
Replace local absolute path by resource
Create additional test output
=> Fix minor java issues

Mustang-CLI/src/main/java/org/mustangproject/commandline/Main.java, library/src/main/java/org/mustangproject/ZUGFeRD/ValidationLogVisualizer.java, library/src/main/resources/stylesheets/result-pdf.xsl
Possibillity to generate a pdf from report xml.
Needs still some refactoring since xsl has no localization and is generally simple without imports etc.
=> #356 Added cli parameter to generate basic pdf version of xml report

library/src/main/resources/stylesheets/result-pdf.xsl
For certain samples the visualization of validation logs fails due to an empty fo:table-body:
> 0. MINIMUM\MINIMUM_Buchungshilfe\factur-x.xml
> 0. MINIMUM\MINIMUM_Rechnung\factur-x.xml
> 1. BASIC WL\BASIC-WL_Einfach\factur-x.xml
> 4. EXTENDED\EXTENDED_Fremdwaehrung\factur-x.xml
> 4. EXTENDED\EXTENDED_InnergemeinschLieferungMehrereBestellungen\factur-x.xml
> 4. EXTENDED\EXTENDED_Kostenrechnung\factur-x.xml
> 4. EXTENDED\EXTENDED_Projektabschlussrechnung\factur-x.xml
> 4. EXTENDED\EXTENDED_Rechnungskorrektur\factur-x.xml
> 4. EXTENDED\EXTENDED_Warenrechnung\factur-x.xml
> 5. XRECHNUNG\XRECHNUNG_Betriebskostenabrechnung\xrechnung.xml
> 5. XRECHNUNG\XRECHNUNG_Einfach\xrechnung.xml
> 5. XRECHNUNG\XRECHNUNG_Elektron\xrechnung.xml
> 5. XRECHNUNG\XRECHNUNG_Reisekostenabrechnung\xrechnung.xml …
=> Fix visualization of validation logs

validator/README.md, validator/src/main/java/org/mustangproject/validator/XMLValidator.java
"too minimal?" instead of "to minimal?"
=> Fix small typos

library/src/main/java/org/mustangproject/DirectDebit.java, library/src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDTradeSettlementDebit.java, library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDInvoiceImporter.java, library/src/test/java/org/mustangproject/ZUGFeRD/DXTest.java, library/src/test/java/org/mustangproject/ZUGFeRD/OXTest.java, library/src/test/java/org/mustangproject/ZUGFeRD/ZF2EdgeTest.java
I tried to fix #516 and allow to set payment means code and payment means description.
I'm not a Java Guy, so be gentle when reviewing :-)
=> allow setting payment means and payment means description, fixes #516

library/src/test/java/org/mustangproject/ZUGFeRD/ZF2EdgeTest.java
=> remove wrong test methods, fixes #653

library/src/main/resources/stylesheets/result-pdf.xsl
=> Optimize validation-report to pdf functionality

library/src/main/java/org/mustangproject/Item.java, library/src/test/java/org/mustangproject/ZUGFeRD/XRTest.java, library/src/test/java/org/mustangproject/ZUGFeRD/ZF2ZInvoiceImporterTest.java
=> Fill TaxExemptionReason during InvoiceImport.

library/src/main/resources/stylesheets/cii-xr.xsl, library/src/main/resources/stylesheets/xr-content.xsl, library/src/test/resources/factur-x-vis.fr.html
Display OccurrenceDateTime (delivery address) in visualizations (HTML and PDF) when only the date is provided instead of the full delivery address.
=> #562 OccurrenceDateTime

library/src/main/java/org/mustangproject/Item.java, library/src/main/java/org/mustangproject/Product.java, library/src/test/java/org/mustangproject/ZUGFeRD/ZF2ZInvoiceImporterTest.java
parses SpecifiedLineTradeSettlement->BillingSpecifiedPeriod to detailedDeliveryPeriod
also fix parser for multiple ApplicableProductCharacteristics
=> Item: add BillingSpecifiedPeriod

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDExporterFromA3.java
fixes #659
do you need example-files for testing?
Greetz, Karsten
=> remove CIDSets from XObjects

library/src/main/java/org/mustangproject/Item.java, library/src/main/java/org/mustangproject/ZUGFeRD/IZUGFeRDExportableItem.java, library/src/test/java/org/mustangproject/ZUGFeRD/ZF2ZInvoiceImporterTest.java
To new field ReceivableSpecifiedTradeAccountingAccount
=> read position accountingReference

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java
=> #771: Added Null check to prevent NullPointerException on Product Description

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java
=> #772: Made Deliver to party name (BT-70) optional to align with specification

library/src/main/java/org/mustangproject/ZUGFeRD/PDFBoxUpdateMitigation.java
Make sure all temporary files are deleted at the end of the JVM session - to fix #775
=> Delete temp file on exit

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDVisualizer.java
=> Correction for "Re-Initialize the HTML-template on language change."

library/src/main/java/org/mustangproject/Product.java, library/src/test/java/org/mustangproject/ZUGFeRD/DeSerializationTest.java, library/src/test/resources/Extended_fremdwaehrung.xml
=> Fix Product Country of origin

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java, validator/src/main/resources/xslt/XR_30/XRechnung-CII-validation.xslt, validator/src/main/resources/xslt/XR_30/XRechnung-UBL-validation.xslt, validator/src/test/java/org/mustangproject/validator/ZUGFeRDValidatorTest.java, validator/src/test/resources/CII_XRechnung_with_Peppol_violation.xml, validator/src/test/resources/validXRV30.xml
Files from xrechnung-3.0.2-bundle-2025-07-10.zip package.
Some tests and test input had to be adjusted for a successful build.
Related to #894.
=> Update validation to XRechnung 3.0.2.

library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDInvoiceImporter.java
fix encoding error when JVM has a standard encoding other than UTF-8
=> fix encoding error in ZUGFeRDInvoiceImporter.java
